name: nuxeo_client
version: 0.0.2
author: Nelson Silva <nelson.silva@inevo.pt>
description: A Client Library for Nuxeo API
homepage: https://github.com/nelsonsilva/nuxeo-dart-client
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  crypto: '>=0.9.0 <0.10.0'
  http: '>=0.10.0 <0.11.0'
  logging: '>=0.9.0 <0.10.0'
  logging_handlers: '>=0.8.0 <0.9.0'
dev_dependencies:
  unittest: '>=0.10.1+2 <0.11.0'

